### ISSUE TITLE
Update plugin to 1.20.4

### ISSUE THREAD

**Issue by PeppoDevStudio** [BoBkiNN/BlockPortals#1]
Update plugin to 1.20.4, please :)

**Comment by PeppoDevStudio** [comment]
Hey?

**Comment by BoBkiNN** [comment]
Are you tested it on 1.20.4? It should work already.

**Comment by PeppoDevStudio** [comment]
Yes but i have this message at console:

[12:52:27 WARN]: [org.bukkit.craftbukkit.v1_20_R3.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[12:52:27 WARN]: java.lang.Exception
[12:52:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.legacy.CraftLegacy.<clinit>(CraftLegacy.java:261)
[12:52:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:397)
[12:52:27 WARN]:        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:119)
[12:52:27 WARN]:        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35)
[12:52:27 WARN]:        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116)
[12:52:27 WARN]:        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38)
[12:52:27 WARN]:        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[12:52:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507)
[12:52:27 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:276)
[12:52:27 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1132)
[12:52:27 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[12:52:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:52:33 WARN]: Legacy plugin BlockPortals v0.2-b5 does not specify an api-version.

**Comment by PeppoDevStudio** [comment]
Couldn't you take it off?

**Comment by BoBkiNN** [comment]
I will fix this error, but does plugin enabled after this anyway?

**Comment by PeppoDevStudio** [comment]
The rest works

**Comment by BoBkiNN** [comment]
Okay thanks

**Comment by BoBkiNN** [comment]
New version must remove this warning
